%%{init: {'theme': 'neutral'}}%%
sequenceDiagram
    participant A as Клијент А
    participant S as Сервер
    participant B as Клијент Б

    A ->> A: оптимистичка примјена измјене
    A ->> S: измјена и идентификатор захтјева
    S ->> S: разрјешавање конфликта и примјена<br/>на ауторитативну копију стања
    S -->> A: прихваћена измјена (потврда)
    S -->> B: прихваћена измјена
    B ->> B: усклађивање са локалним<br/>непотврђеним измјенама и примјена
